spring:
  application:
    name: admin-bff

server:
  port: 8093

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  clients:
    billing-service-base-url: http://localhost:8084
    insurance-service-base-url: http://localhost:8087
    auth-service-base-url: http://localhost:8085
    notification-service-base-url: http://localhost:8088