FROM maven:3.9.8-eclipse-temurin-21 AS build

ARG MODULE_PATH
WORKDIR /workspace
COPY . .
RUN mvn -q -f ${MODULE_PATH}/pom.xml -DskipTests package

FROM eclipse-temurin:21-jre

ARG MODULE_PATH
WORKDIR /app
COPY --from=build /workspace/${MODULE_PATH}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]