spring:
  application:
    name: pharmacy-service
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:pharmacy_db}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Compas@123}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html