spring:
  application:
    name: web-bff

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  clients:
    patient-service-base-url: http://localhost:8081
    appointment-service-base-url: http://localhost:8082
    health-record-service-base-url: http://localhost:8083
    auth-service-base-url: http://localhost:8085