CREATE DATABASE IF NOT EXISTS patient_db;
CREATE DATABASE IF NOT EXISTS appointment_db;
CREATE DATABASE IF NOT EXISTS health_record_db;
CREATE DATABASE IF NOT EXISTS billing_db;
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS pharmacy_db;
CREATE DATABASE IF NOT EXISTS insurance_db;
CREATE DATABASE IF NOT EXISTS notification_db;